### ISSUE TITLE
Advance healthcheck

### ISSUE THREAD

**Issue by munir131** [Improwised/golang-api#201]
# Fiber added advanced health check in 2.52.0
https://docs.gofiber.io/api/middleware/healthcheck/

## Acceptance criteria
- [ ] How it is advance than our healthcheck?
- [ ] What they are checking in Readiness probe?
- [ ] Can we add our third-party services to Readiness probe?

**Comment by chintansakhiya** [comment]
#### Fiber advanced health check in 2.52.0
- The Fiber health check feature in Fiber allows for the `simultaneous checking` of multiple services through a single endpoint, streamlining the process of monitoring various services, just like our `healthz/`overall health check.
- It does not provide individual health checks. like `healthz/db`
- In the readiness probe, Fiber checks the availability of a service by determining whether it is ready or not, returning a boolean value accordingly. This is achieved through the function func(c *fiber.Ctx) bool {}.
- Instead of returning error messages, Fiber's health check simply indicates whether the server is okay or unavailable, simplifying the response handling.
- Yes, it is possible to integrate third-party services into the readiness probe, enabling comprehensive monitoring of all relevant components.

**Comment by munir131** [comment]
@chintansakhiya Looks like, our implementation is near to them. So, no need to move on those.
